# Server Port
server.port=8080

# Spring Data MongoDB Configuration
# Local MongoDB connection URI (default port is 27017)
spring.data.mongodb.uri=mongodb+srv://sundar07:1234@cluster07.sbtfbhv.mongodb.net/?appName=Cluster07

# Enable detailed logging for debugging if needed
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.packinglist=DEBUG
